services:
    oro_cybersource.event_listener.callback.cybersource_checkout:
        class: 'Oro\Bundle\CyberSourceBundle\EventListener\Callback\CyberSourceCheckoutListener'
        lazy: true
        arguments:
            - '@session'
            - '@oro_cybersource.method.cybersource.provider'
            - '@oro_payment.provider.result_messages'
        calls:
            - ['setLogger', ['@logger']]
        tags:
            - { name: kernel.event_listener, event: oro_payment.callback.error, method: onError }
            - { name: kernel.event_listener, event: oro_payment.callback.return, method: onReturn }
